apikey: <Virus Total API Key> (string, mandatory)
input: <CSV file> (file path, Mandatory)
output: <CSV file> (file path, Mandatory)
expire: <expire after this number of days> (integer, mandatory)
action: <block or log>> (mandatory)
proxy: <proxy address (url, optional)
threads: <number of parallel connections to Virus Total> (integer, optional)