// Code generated by enum (github.com/mpkondrashin/enum) using following command:
// enum -package apex -type ObjectType -names ip,domain,url,sha1,sha256
// DO NOT EDIT!

package apex

import (
    "encoding/json"
    "errors"
    "fmt"
    "strconv"
    "strings"
)

type ObjectType int

const (
    ObjectTypeIp     ObjectType = iota
    ObjectTypeDomain ObjectType = iota
    ObjectTypeUrl    ObjectType = iota
    ObjectTypeSha1   ObjectType = iota
    ObjectTypeSha256 ObjectType = iota
)


// String - return string representation for ObjectType value
func (v ObjectType)String() string {
    s, ok := map[ObjectType]string {
         ObjectTypeIp:     "ip",
         ObjectTypeDomain: "domain",
         ObjectTypeUrl:    "url",
         ObjectTypeSha1:   "sha1",
         ObjectTypeSha256: "sha256",
    }[v]
    if ok {
        return s
    }
    return "ObjectType(" + strconv.FormatInt(int64(v), 10) + ")"
}

// ErrUnknownObjectType - will be returned wrapped when parsing string
// containing unrecognized value.
var ErrUnknownObjectType = errors.New("unknown ObjectType")


var mapObjectTypeFromString = map[string]ObjectType{
    "ip":    ObjectTypeIp,
    "domain":    ObjectTypeDomain,
    "url":    ObjectTypeUrl,
    "sha1":    ObjectTypeSha1,
    "sha256":    ObjectTypeSha256,
}

// UnmarshalJSON implements the Unmarshaler interface of the json package for ObjectType.
func (s *ObjectType) UnmarshalJSON(data []byte) error {
    var v string
    if err := json.Unmarshal(data, &v); err != nil {
        return err
    }
    result, ok := mapObjectTypeFromString[strings.ToLower(v)]
    if !ok {
        return fmt.Errorf("%w: %s", ErrUnknownObjectType, v)
    }
    *s = result
    return nil
}

// MarshalJSON implements the Marshaler interface of the json package for ObjectType.
func (s ObjectType) MarshalJSON() ([]byte, error) {
    return []byte(fmt.Sprintf("\"%v\"", s)), nil
}

// UnmarshalYAML implements the Unmarshaler interface of the yaml.v3 package for ObjectType.
func (s *ObjectType) UnmarshalYAML(unmarshal func(interface{}) error) error {
    var v string
    if err := unmarshal(&v); err != nil {
        return err
    }
    result, ok := mapObjectTypeFromString[strings.ToLower(v)]  
    if !ok {
        return fmt.Errorf("%w: %s", ErrUnknownObjectType, v)
    }
    *s = result
    return nil
}
