name: Go
on: [push]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3

    - name: Check Go version
      run: go version

    - name: Tests
      run: go test ./...

    - name: Build ACentral for Windows
      run: |
        GOOS=windows GOARCH=amd64 go build ./cmd/acentral
        GOOS=windows GOARCH=amd64 go build ./cmd/convert
        GOOS=windows GOARCH=amd64 go build ./cmd/filter
      
    - name: Pack for Windows
      uses: montudor/action-zip@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        args: zip -j "tmdetect_win64_${{ github.ref_name }}.zip" acentral.exe convert.exe filter.exe README.md cmd/filter/filter_config_example.yaml cmd/acentral/acentral_config_example.yaml

    - name: Build ACentral for Linux
      run: |
        GOOS=linux GOARCH=amd64 go build ./cmd/acentral
        GOOS=linux GOARCH=amd64 go build ./cmd/convert
        GOOS=linux GOARCH=amd64 go build ./cmd/filter
        
    - name: Pack for Linux
      uses: montudor/action-zip@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        args: zip -j "tmdetect_linux64_${{ github.ref_name }}.zip" acentral convert filter README.md cmd/filter/filter_config_example.yaml cmd/acentral/acentral_config_example.yaml
          
    - name: Build ACentral for macOS Intel
      run: |
        GOOS=darwin GOARCH=amd64 go build ./cmd/acentral
        GOOS=darwin GOARCH=amd64 go build ./cmd/convert
        GOOS=darwin GOARCH=amd64 go build ./cmd/filter
          
    - name: Pack for macOS Intel
      uses: montudor/action-zip@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        args: zip -j "tmdetect_macos_intel_${{ github.ref_name }}.zip" acentral convert filter README.md cmd/filter/filter_config_example.yaml cmd/acentral/acentral_config_example.yaml
            
    - name: Build ACentral for macOS ARM
      run: |
        GOOS=darwin GOARCH=arm64 go build ./cmd/acentral
        GOOS=darwin GOARCH=arm64 go build ./cmd/convert
        GOOS=darwin GOARCH=arm64 go build ./cmd/filter
              
    - name: Pack for macOS ARM
      uses: montudor/action-zip@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        args: zip -j "tmdetect_macos_m_${{ github.ref_name }}.zip" acentral convert filter README.md cmd/filter/filter_config_example.yaml cmd/acentral/acentral_config_example.yaml
    
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          tmdetect_win64_${{ github.ref_name }}.zip
          tmdetect_linux64_${{ github.ref_name }}.zip
          tmdetect_macos_intel_${{ github.ref_name }}.zip
          tmdetect_macos_m_${{ github.ref_name }}.zip